name: GitHub Actions
on:
  repository_dispatch:
    types: [file-uploaded]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Download markdown file
      run: |
      curl \
      -H "Accept: application/vnd.github.v3+json" \
      https://api.github.com/repos/dev-daeun/openapi-to-markdown/actions/artifacts/
