name: GitHub Actions
on:
  repository_dispatch:
    types: [file-uploaded]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Download markdown file
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.ACTION_ACCESS_TOKEN}}
        workflow_conclusion: success
        name: openapi-doc
        repo: dev-daeun/openapi-to-markdown
